### PR TITLE
/meme command

### PR DESCRIPTION
**Pull request by SpeedLight-Dev**
Before this edit, the slash command for memes was `/reddit`. Now it's `/meme` (I find it more intuitive).

### CODE REVIEW

**Comment by ghost** [comment]
yeah i think open should commit this

**Comment by thatjar** [comment]
it was called reddit because you can use any subreddit, but sure I guess

**Comment by SpeedLight-Dev** [comment]
> it was called reddit because you can use any subreddit, but sure I guess

Yes ok, but probably people don't think that the meme command could be "reddit".

**Comment by thatjar** [comment]
ok

**Pull request merged**
